# POST http://localhost:3000/watchlist/create HTTP/1.1
# Content-Type: application/json

# {
#     "watchlistName": "My Watchlist Nº 5"
# }


POST http://localhost:3000/watchlist/add/655c8632ab28341aec52486c HTTP/1.1
Content-Type: application/json

{
    "account": "JELZJBBZDH3XJGUCQC6HICGWYGJC5QAGNZUK7ZJTUQCJLXNATXPM52SKNE"
}

# GET  http://localhost:3000/watchlist/accounts/655bfa872f093dcdf2e542ef HTTP/1.1