# POST http://localhost:3000/watchlist/create HTTP/1.1
# Content-Type: application/json

# {
#     "watchlistName": "My Watchlist Nº 2"
# }


POST http://localhost:3000/watchlist/add/655bde54ebc0f66042924fe5 HTTP/1.1
Content-Type: application/json

{
    "account": "RXY4EBDWFVL4JPGUICFU7JRMRPGZFTSGQLU6XLUJ2A3DVODGKEI2PRX5Y4"
}

# GET  http://localhost:3000/watchlist/accounts/655bde54ebc0f66042924fe5 HTTP/1.1