# POST http://localhost:3000/watchlist/create HTTP/1.1
# Content-Type: application/json

# {
#     "watchlistName": "My Definite Watchlist"
# }


# POST http://localhost:3000/watchlist/add/xxxxxx HTTP/1.1
# Content-Type: application/json

# {
#     "account": "xxxxxx"
# }

# GET  http://localhost:3000/watchlist/accounts/xxxxxx HTTP/1.1